/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Converter.types";
import * as _1 from "./Converter.client";
import * as _2 from "./Converter.message-composer";
import * as _3 from "./Converter.react-query";
import * as _4 from "./Converter.provider";
import * as _5 from "./SimplePriceFeed.types";
import * as _6 from "./SimplePriceFeed.client";
import * as _7 from "./SimplePriceFeed.message-composer";
import * as _8 from "./SimplePriceFeed.react-query";
import * as _9 from "./SimplePriceFeed.provider";
import * as _10 from "./VirtualStaking.types";
import * as _11 from "./VirtualStaking.client";
import * as _12 from "./VirtualStaking.message-composer";
import * as _13 from "./VirtualStaking.react-query";
import * as _14 from "./VirtualStaking.provider";
import * as _15 from "./ExternalStaking.types";
import * as _16 from "./ExternalStaking.client";
import * as _17 from "./ExternalStaking.message-composer";
import * as _18 from "./ExternalStaking.react-query";
import * as _19 from "./ExternalStaking.provider";
import * as _20 from "./NativeStaking.types";
import * as _21 from "./NativeStaking.client";
import * as _22 from "./NativeStaking.message-composer";
import * as _23 from "./NativeStaking.react-query";
import * as _24 from "./NativeStaking.provider";
import * as _25 from "./StakingProxy.types";
import * as _26 from "./StakingProxy.client";
import * as _27 from "./StakingProxy.message-composer";
import * as _28 from "./StakingProxy.react-query";
import * as _29 from "./StakingProxy.provider";
import * as _30 from "./Vault.types";
import * as _31 from "./Vault.client";
import * as _32 from "./Vault.message-composer";
import * as _33 from "./Vault.react-query";
import * as _34 from "./Vault.provider";
export namespace contracts {
  export const Converter = { ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._4
  };
  export const SimplePriceFeed = { ..._5,
    ..._6,
    ..._7,
    ..._8,
    ..._9
  };
  export const VirtualStaking = { ..._10,
    ..._11,
    ..._12,
    ..._13,
    ..._14
  };
  export const ExternalStaking = { ..._15,
    ..._16,
    ..._17,
    ..._18,
    ..._19
  };
  export const NativeStaking = { ..._20,
    ..._21,
    ..._22,
    ..._23,
    ..._24
  };
  export const StakingProxy = { ..._25,
    ..._26,
    ..._27,
    ..._28,
    ..._29
  };
  export const Vault = { ..._30,
    ..._31,
    ..._32,
    ..._33,
    ..._34
  };
}