/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { ConverterClient, ConverterQueryClient } from "./Converter.client";
import { ConverterMessageComposer } from "./Converter.message-composer";
export class Converter extends ContractBase<ConverterClient, ConverterQueryClient, ConverterMessageComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, ConverterClient, ConverterQueryClient, ConverterMessageComposer);
  }

}