/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { ExternalStakingClient, ExternalStakingQueryClient } from "./ExternalStaking.client";
import { ExternalStakingMessageComposer } from "./ExternalStaking.message-composer";
export class ExternalStaking extends ContractBase<ExternalStakingClient, ExternalStakingQueryClient, ExternalStakingMessageComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, ExternalStakingClient, ExternalStakingQueryClient, ExternalStakingMessageComposer);
  }

}