/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { SimplePriceFeedClient, SimplePriceFeedQueryClient } from "./SimplePriceFeed.client";
import { SimplePriceFeedMessageComposer } from "./SimplePriceFeed.message-composer";
export class SimplePriceFeed extends ContractBase<SimplePriceFeedClient, SimplePriceFeedQueryClient, SimplePriceFeedMessageComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, SimplePriceFeedClient, SimplePriceFeedQueryClient, SimplePriceFeedMessageComposer);
  }

}