/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  [k: string]: unknown;
}
export type ExecuteMsg = VirtualStakingApiExecMsg | ExecMsg;
export type VirtualStakingApiExecMsg = {
  bond: {
    amount: Coin;
    validator: string;
    [k: string]: unknown;
  };
} | {
  unbond: {
    amount: Coin;
    validator: string;
    [k: string]: unknown;
  };
};
export type Uint128 = string;
export type ExecMsg = string;
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = VirtualStakingApiQueryMsg | QueryMsg1;
export type VirtualStakingApiQueryMsg = string;
export type QueryMsg1 = {
  config: {
    [k: string]: unknown;
  };
};
export interface ConfigResponse {
  converter: string;
  denom: string;
}