/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, VirtualStakingApiExecMsg, Uint128, ExecMsg, Coin, QueryMsg, VirtualStakingApiQueryMsg, QueryMsg1, ConfigResponse } from "./VirtualStaking.types";
export interface VirtualStakingMessage {
  contractAddress: string;
  sender: string;
  bond: ({
    amount,
    validator
  }: {
    amount: Coin;
    validator: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unbond: ({
    amount,
    validator
  }: {
    amount: Coin;
    validator: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class VirtualStakingMessageComposer implements VirtualStakingMessage {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.bond = this.bond.bind(this);
    this.unbond = this.unbond.bind(this);
  }

  bond = ({
    amount,
    validator
  }: {
    amount: Coin;
    validator: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          bond: {
            amount,
            validator
          }
        })),
        funds: _funds
      })
    };
  };
  unbond = ({
    amount,
    validator
  }: {
    amount: Coin;
    validator: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unbond: {
            amount,
            validator
          }
        })),
        funds: _funds
      })
    };
  };
}