/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { UseQueryOptions, UseMutationOptions } from "@tanstack/react-query";
import { ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee, Coin } from "@cosmjs/amino";
import { Decimal, ConfigResponse, PriceResponse } from "./SimplePriceFeed.types";
import { SimplePriceFeedQueryClient, SimplePriceFeedClient } from "./SimplePriceFeed.client";
export interface SimplePriceFeedReactQuery<TResponse, TData = TResponse> {
    client: SimplePriceFeedQueryClient;
    options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
        initialData?: undefined;
    };
}
export interface SimplePriceFeedConfigQuery<TData> extends SimplePriceFeedReactQuery<ConfigResponse, TData> {
}
export declare function useSimplePriceFeedConfigQuery<TData = ConfigResponse>({ client, options }: SimplePriceFeedConfigQuery<TData>): any;
export interface SimplePriceFeedPriceQuery<TData> extends SimplePriceFeedReactQuery<PriceResponse, TData> {
}
export declare function useSimplePriceFeedPriceQuery<TData = PriceResponse>({ client, options }: SimplePriceFeedPriceQuery<TData>): any;
export interface SimplePriceFeedUpdatePriceMutation {
    client: SimplePriceFeedClient;
    msg: {
        nativePerForeign: Decimal;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useSimplePriceFeedUpdatePriceMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, SimplePriceFeedUpdatePriceMutation>, "mutationFn">): any;
