/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Decimal, ConfigResponse, PriceResponse } from "./SimplePriceFeed.types";
export interface SimplePriceFeedReadOnlyInterface {
    contractAddress: string;
    price: () => Promise<PriceResponse>;
    config: () => Promise<ConfigResponse>;
}
export declare class SimplePriceFeedQueryClient implements SimplePriceFeedReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    price: () => Promise<PriceResponse>;
    config: () => Promise<ConfigResponse>;
}
export interface SimplePriceFeedInterface extends SimplePriceFeedReadOnlyInterface {
    contractAddress: string;
    sender: string;
    updatePrice: ({ nativePerForeign }: {
        nativePerForeign: Decimal;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class SimplePriceFeedClient extends SimplePriceFeedQueryClient implements SimplePriceFeedInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    updatePrice: ({ nativePerForeign }: {
        nativePerForeign: Decimal;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
