/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export declare type Decimal = string;
export interface InstantiateMsg {
    native_per_foreign: Decimal;
    owner?: string | null;
    [k: string]: unknown;
}
export declare type ExecuteMsg = PriceFeedApiExecMsg | ExecMsg;
export declare type PriceFeedApiExecMsg = string;
export declare type ExecMsg = {
    update_price: {
        native_per_foreign: Decimal;
        [k: string]: unknown;
    };
};
export declare type QueryMsg = PriceFeedApiQueryMsg | QueryMsg1;
export declare type PriceFeedApiQueryMsg = {
    price: {
        [k: string]: unknown;
    };
};
export declare type QueryMsg1 = {
    config: {
        [k: string]: unknown;
    };
};
export interface ConfigResponse {
    native_per_foreign: Decimal;
    owner: string;
}
export interface PriceResponse {
    native_per_foreign: Decimal;
}
