/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { Decimal } from "./SimplePriceFeed.types";
export interface SimplePriceFeedMessage {
    contractAddress: string;
    sender: string;
    updatePrice: ({ nativePerForeign }: {
        nativePerForeign: Decimal;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class SimplePriceFeedMessageComposer implements SimplePriceFeedMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    updatePrice: ({ nativePerForeign }: {
        nativePerForeign: Decimal;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
