/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export interface InstantiateMsg {
    denom: string;
    owner: string;
    validator: string;
    [k: string]: unknown;
}
export declare type ExecuteMsg = ExecMsg;
export declare type ExecMsg = {
    stake: {
        validator: string;
        [k: string]: unknown;
    };
} | {
    restake: {
        amount: Coin;
        dst_validator: string;
        src_validator: string;
        [k: string]: unknown;
    };
} | {
    vote: {
        proposal_id: number;
        vote: VoteOption;
        [k: string]: unknown;
    };
} | {
    vote_weighted: {
        proposal_id: number;
        vote: WeightedVoteOption[];
        [k: string]: unknown;
    };
} | {
    withdraw_rewards: {
        [k: string]: unknown;
    };
} | {
    unstake: {
        amount: Coin;
        validator: string;
        [k: string]: unknown;
    };
} | {
    release_unbonded: {
        [k: string]: unknown;
    };
};
export declare type Uint128 = string;
export declare type VoteOption = "yes" | "no" | "abstain" | "no_with_veto";
export declare type Decimal = string;
export interface Coin {
    amount: Uint128;
    denom: string;
    [k: string]: unknown;
}
export interface WeightedVoteOption {
    option: VoteOption;
    weight: Decimal;
    [k: string]: unknown;
}
export declare type QueryMsg = QueryMsg1;
export declare type QueryMsg1 = {
    config: {
        [k: string]: unknown;
    };
};
export declare type Addr = string;
export interface Config {
    denom: string;
    owner: Addr;
    parent: Addr;
}
