/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { Coin } from "./VirtualStaking.types";
export interface VirtualStakingMessage {
    contractAddress: string;
    sender: string;
    bond: ({ amount, validator }: {
        amount: Coin;
        validator: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    unbond: ({ amount, validator }: {
        amount: Coin;
        validator: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class VirtualStakingMessageComposer implements VirtualStakingMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    bond: ({ amount, validator }: {
        amount: Coin;
        validator: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    unbond: ({ amount, validator }: {
        amount: Coin;
        validator: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
