/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ContractBase, IContractConstructor } from "./contractContextBase";
import { VirtualStakingClient, VirtualStakingQueryClient } from "./VirtualStaking.client";
import { VirtualStakingMessageComposer } from "./VirtualStaking.message-composer";
export declare class VirtualStaking extends ContractBase<VirtualStakingClient, VirtualStakingQueryClient, VirtualStakingMessageComposer> {
    constructor({ address, cosmWasmClient, signingCosmWasmClient }: IContractConstructor);
}
